### ISSUE TITLE
claude stream缺失event

### ISSUE THREAD

**Issue by RedwindA** [Calcium-Ion/new-api-horizon#6]
根据[文档](https://docs.anthropic.com/en/api/messages-streaming)，stream中应该包含`message_start`、`content_block_start` 、`content_block_delta `类型的event，但使用Postman请求时未接收到上述event，使用客户端LibreChat也未接收到流式消息的正文。

![image](https://github.com/user-attachments/assets/daa91610-4f8a-4122-8b52-67412484eb16)

图一是向new api horizon发起请求

![image](https://github.com/user-attachments/assets/5c4d215d-89a1-44f4-8c92-3fd34a0d343b)

图二是向Rix API发起请求

**Comment by Calcium-Ion** [comment]
你的渠道是通过OpenAI格式接入还是Claude格式

**Comment by RedwindA** [comment]
> 你的渠道是通过OpenAI格式接入还是Claude格式

OpenAI

**Comment by Calcium-Ion** [comment]
已修复，晚点发版，可以先用Claude格式接没问题

**Comment by RedwindA** [comment]
更新到新版之后event 类型都全了，但是正文最开始的delta块似乎是被吞了

如图，让它从1数到10的时候，开始的123没有了

![image](https://github.com/user-attachments/assets/1afe8a3f-d15e-48af-8a44-f800345266e9)

**Comment by Calcium-Ion** [comment]
我这边暂时无法复现，OpenAI渠道接入上游

![image](https://github.com/user-attachments/assets/400458d5-12c8-4c01-a7fd-3c5fd206fba2)

**Comment by Calcium-Ion** [comment]
如果还是有问题的话，可以加群私发一下渠道给我试试
