### ISSUE TITLE
怎么开启RealTime功能

### ISSUE THREAD

**Issue by hxxb** [Calcium-Ion/new-api-horizon#8]
我在chatgpt-web-midjourney-proxy项目中使用RealTime提示websocket 连接服务器错误！
![image](https://github.com/user-attachments/assets/f5871f88-9cce-4e2f-b3b3-6c9e704b9c84)

**Comment by Calcium-Ion** [comment]
需要nginx配置websocket和cdn支持

**Comment by hxxb** [comment]
好的 可以了 
再nginx的localtion块中 加入如下配置即可

proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
