### ISSUE TITLE
移除 gemini 多余的响应字段

### ISSUE THREAD

**Issue by QAbot-zh** [Calcium-Ion/new-api-horizon#9]
gemini 系列模型的响应会多出一个 error 字段：

<p style="display: flex; justify-content: space-between;">
  <img src="https://github.com/user-attachments/assets/0407bee4-5104-4d0c-a247-bfc05c95c368" alt="Image 1" width="300" />
  <img src="https://github.com/user-attachments/assets/d188421f-8a04-4c2a-9207-400a05a7c778" alt="Image 2" width="300" />
</p>

非 gemini 模型则没有这个情况：

<p style="display: flex; justify-content: space-between;">
  <img src="https://github.com/user-attachments/assets/aa6dfbd8-5b93-406f-971e-c30747d0b1d3" alt="Image 1" width="300" />
  <img src="https://github.com/user-attachments/assets/45e99822-f862-4392-9226-cac17817a12e" alt="Image 2" width="300" />
</p>

这字段是必要的吗，没有必要的话希望可以移除

**Comment by Calcium-Ion** [comment]
已修复，请等待新版本
